version: 2.1
orbs:
  python: circleci/python@1.2

workflows:
  build-app-with-test:
    jobs:
      - build-and-test
      - deploy
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipefile"}}
      - run:
          name: Install dependencies
          command: |
            pipenv --three
            pipenv install

      - save_cache:
          key:
            deps1-{{ .Branch }}-{{ checksum "Pipefile"}} 
          paths:
            - "venv"
      - run:
          name: Run tests
          command: pipenv run pytest
  deploy:
    
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - 0e:d6:93:fd:03:f0:54:b5:6b:57:8e:44:cd:0d:b3:99
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST "cd automating-flask-deployments-with-pythonanywhere; git pull";
